#!/bin/bash

# TRW Countdown - Environment Setup Script
# This script helps you create a .env file with your Firebase credentials

echo "🔥 TRW Countdown - Firebase Setup"
echo "=================================="
echo ""
echo "This script will help you create a .env file with your Firebase credentials."
echo "You can find these values in your Firebase Console:"
echo "  → Project Settings → Your Apps → Web App Config"
echo ""

# Check if .env already exists
if [ -f .env ]; then
    echo "⚠️  Warning: .env file already exists!"
    read -p "Do you want to overwrite it? (y/n): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "Setup cancelled."
        exit 0
    fi
fi

echo ""
echo "Please enter your Firebase credentials:"
echo ""

# Read Firebase API Key
read -p "Firebase API Key: " api_key
while [ -z "$api_key" ]; do
    echo "API Key cannot be empty."
    read -p "Firebase API Key: " api_key
done

# Read Auth Domain
read -p "Auth Domain (e.g., your-project.firebaseapp.com): " auth_domain
while [ -z "$auth_domain" ]; do
    echo "Auth Domain cannot be empty."
    read -p "Auth Domain: " auth_domain
done

# Read Project ID
read -p "Project ID: " project_id
while [ -z "$project_id" ]; do
    echo "Project ID cannot be empty."
    read -p "Project ID: " project_id
done

# Read Storage Bucket
read -p "Storage Bucket (e.g., your-project.appspot.com): " storage_bucket
while [ -z "$storage_bucket" ]; do
    echo "Storage Bucket cannot be empty."
    read -p "Storage Bucket: " storage_bucket
done

# Read Messaging Sender ID
read -p "Messaging Sender ID: " sender_id
while [ -z "$sender_id" ]; do
    echo "Messaging Sender ID cannot be empty."
    read -p "Messaging Sender ID: " sender_id
done

# Read App ID
read -p "App ID: " app_id
while [ -z "$app_id" ]; do
    echo "App ID cannot be empty."
    read -p "App ID: " app_id
done

# Create .env file
cat > .env << EOF
# Firebase Configuration
# Generated by setup-env.sh on $(date)

VITE_FIREBASE_API_KEY=$api_key
VITE_FIREBASE_AUTH_DOMAIN=$auth_domain
VITE_FIREBASE_PROJECT_ID=$project_id
VITE_FIREBASE_STORAGE_BUCKET=$storage_bucket
VITE_FIREBASE_MESSAGING_SENDER_ID=$sender_id
VITE_FIREBASE_APP_ID=$app_id
EOF

echo ""
echo "✅ Success! Your .env file has been created."
echo ""
echo "Next steps:"
echo "  1. Review your .env file to make sure all values are correct"
echo "  2. Start (or restart) the development server: npm run dev"
echo "  3. Open http://localhost:5173 in your browser"
echo ""
echo "⚠️  Important: Never commit your .env file to version control!"
echo ""

